# Generated by Django 2.1.5 on 2019-03-22 00:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ColonyElements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.SmallIntegerField(default=0)),
                ('form', models.PositiveSmallIntegerField(choices=[(1, 'Puntiforme'), (2, 'Circular'), (3, 'Irregular'), (4, 'Rizoide'), (5, 'Fusiforme')], default=1)),
                ('surface', models.PositiveSmallIntegerField(choices=[(1, 'Lisa'), (2, 'Rugosa'), (3, 'Plegada')], default=1)),
                ('edge', models.PositiveSmallIntegerField(choices=[(1, 'Redondeado'), (2, 'Ondulado'), (3, 'Lobulado'), (4, 'Filamentoso')], default=1)),
                ('elevation', models.PositiveSmallIntegerField(choices=[(1, 'Plana'), (2, 'Convexa'), (3, 'Elevada')], default=1)),
                ('color', models.CharField(max_length=50)),
                ('size', models.SmallIntegerField(default=0)),
                ('growth', models.PositiveSmallIntegerField(choices=[(1, 'Sin Crecimiento'), (2, 'Crecimiento Regular'), (3, 'Crecimient Abundante')], default=1)),
                ('observation', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ColonyProyect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('colony_elements', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colony_elements_proyect', to='api.ColonyElements')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colony_proyect_user', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', stdimage.models.StdImageField(default='usuarios/avatar.png', upload_to='usuarios/%Y/%m/')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoColony',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('created', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo_colony_user', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
            ],
        ),
        migrations.AddField(
            model_name='colonyelements',
            name='photography',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo_colony_elements', to='api.PhotoColony'),
        ),
    ]
