# Generated by Django 2.1.5 on 2019-03-22 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colonyproyect',
            name='colony_elements',
        ),
        migrations.AddField(
            model_name='colonyelements',
            name='proyect',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colony_elements_proyect', to='api.ColonyProyect'),
        ),
    ]
