# Generated by Django 2.1.5 on 2019-03-24 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190322_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colonyproyect',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
    ]
