# Generated by Django 2.1.5 on 2019-03-24 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190324_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colonyproyect',
            name='url_imagen',
            field=models.URLField(default='https://res.cloudinary.com/rogerarjona/image/upload/c_thumb,w_200,g_face/v1553401632/colony_default.png', null=True),
        ),
    ]
