# Generated by Django 2.1.5 on 2019-03-24 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190324_0018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photocolony',
            name='url',
        ),
        migrations.AddField(
            model_name='colonyproyect',
            name='url_thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photocolony',
            name='proyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo_colony_proyecto', to='api.ColonyProyect'),
        ),
        migrations.AddField(
            model_name='photocolony',
            name='url_contado',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photocolony',
            name='url_imagen',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photocolony',
            name='url_thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
