# Generated by Django 2.1.5 on 2019-03-25 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190324_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='photocolony',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
