# Generated by Django 2.1.5 on 2019-03-27 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_photocolony_url_contado_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colonyelements',
            name='color',
            field=models.CharField(default='', max_length=50),
        ),
    ]
