# Generated by Django 2.1.5 on 2019-03-28 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190327_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colonyproyect',
            name='url_thumbnail',
            field=models.URLField(blank=True, default='https://res.cloudinary.com/rogerarjona/image/upload/w_1000,c_fill,ar_1:1,g_auto,r_max,bo_5px_solid_red,b_rgb:262c35/v1553404423/colony_300_default.png', null=True),
        ),
    ]
